# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='charge_day',
            field=models.IntegerField(null=True),
        ),
    ]
