# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20180915_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('product', models.ManyToManyField(to='stock.Product')),
            ],
            options={
                'db_table': 'stockoperation',
            },
        ),
    ]
